export const PATH = {
  SIGN_UP: '/sign-up',
  SIGN_UP_WITH_GOOGLE: '/google/sign-up',
  SIGN_IN: '/sign-in',
  GOOGLE_REDIRECT: '/google-redirect',
  HOME: '/',
  VERIFICATION: '/activation/:link',
  FORGOT_PASS: '/forgot-pass',
  CONFIRM: '/forgot-pass/confirm',
  RESET_PASS: '/reset-pass/:token',
  PROFILE: '/profile',
  HELP: '/help',
  DASHBOARD: '/dashboard',
  CREATE_PATIENT: '/create-patient',
  EDIT_PATIENT: '/edit-patient/:id',
  SCHEDULER: '/scheduler',
  BOOK_APPOINTMENT: '/book-appointment/:id',
  AVAILABILITY: '/availability',
  PATIENTS: '/patients',
  PATIENT_CARD: '/patient/:id',
  APPOINTMENTS: '/appointments',
  NOT_FOUND: '/not-found',
  ZOOM: '/zoom',
  CHAT: '/chat'
};
